export const ADD_USER = 'ADD_USER'
export const USER_LEFT = 'USER_LEFT'
export const TOGGLE_CHAT = 'TOGGLE_CHAT'
export const TOGGLE_ROOM_ADMIN = 'TOGGLE_ROOM_ADMIN'
export const SET_ROOM_ID = 'SET_ROOM_ID'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const INPUT_CHANGE = 'INPUT_CHANGE'
